### ISSUE TITLE
(Future) Allow multiple verify requests on the same connection

### ISSUE THREAD

**Issue by jsaur** [kiva/aries-controller#110]
In order to support our honduras use case, we may need to have multiple proof requests across the same connection, ie only one fingerprint but multiple proof requests for RNP data + FSP data, etc.

**Comment by matt-raffel-kiva** [comment]
@jsaur can you explain why we need this please?  (benefit, problem it solves etc...)

**Comment by jsaur** [comment]
Good question, this ticket may be able to be closed as won't do. The original idea is that we may want the KYC flow to be broken up into a few different steps, ie one mandatory credential exchange for the RNP identity credential and another opportunistic one for FSP data (if they don't have one of these credentials the check doesn't fail, its just bonus). And the user would just fingerprint once at the beginning for all subsequent credential exchanges. @margojohnson24 what do you think, do we still need to support this use case anymore?

**Comment by matt-raffel-kiva** [comment]
just got an email from Stephan Curran and some changes coming, including this:  https://github.com/hyperledger/aries-rfcs/tree/main/features/0434-outofband.  Interesting to note:  "We need the ability to reuse a connection."   See the connection reuse for more information.

**Comment by margojohnson24** [comment]
@jsaur if I'm following this is the use case you are describing:

"A client walks into a bank to request a line of credit. They go through the KYC check with the teller, including providing their fingerprint and national ID number to return their identity data. The teller is subsequently able to request and receive some additional income records that the client also held in their wallet. This is important evidence for loan approval." 

The key factor here is multiple proof requests across the same established connection.

The alternative is that the client has to re-authenticate for each subsequent request (i.e. give their fingerprint again), correct? While slightly cumbersome, I don't see this as an immediate blocker - particularly as scanning that fingerprint starts to become a consent pattern. 

Also, could the original proof request not to contain multiple asks i.e. "give me identity credentials plus any credentials with financial data for this time frame" ...

**Comment by jsaur** [comment]
This isn't being prioritized any time soon, but leaving around because there's some interesting comments. I also just wanted to call out 2 different scenarios, the first one is the one this ticket is concerned with:
1) The user authenticates with the key guardian (eg via fingerprint), we open an agent connection for x minutes, and the verifier can execute multiple proof requests using this same connection. This is supported by aca-py currently, but not by our system, as we would need to add a way to save the connection id correlated with a given "session id" on the front end (or something like that).
2) The transaction reporting use case where we want both a single connection and a single proof request, but we able to send over multiple proofs (ie from multiple credentials) that all match the given proof request (eg send me all your chained transactions). This functionality isn't in aca-py yet, but I believe it's on their radar.

**Comment by matt-raffel-kiva** [comment]
closing due to project shutdown
