### ISSUE TITLE
Support loading profile files via environment / k8s secrets

### ISSUE THREAD

**Issue by voutasaurus** [kiva/aries-controller#99]
Solution:
Set two environment variables for every file, one is a path, the other is contents. The contents are base64 encoded and this decodes it on startup and writes the file to that path. This way you can have one image for most of the controllers and just overwrite the profile on startup.

Example Go code (as an example, taken from another project of mine):

```
package main

import (
	"encoding/base64"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
)

func envToFile(b64, path string) error {
	b, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0777); err != nil {
		return err
	}
	return ioutil.WriteFile(path, b, 0666)
}

func requireFile(b64, path string) {
	if err := envToFile(b64, path); err != nil {
		log.Fatalln("could not write to", path, ". error:", err)
	}
}
```

This issue is to write something like this in typescript for aries-controller to generate files on startup from environment variables.

**Comment by voutasaurus** [comment]
The benefit of this approach is that we will need less customization in the docker images of individual controllers, as all the custom profile configuration can be supplied via the command line.

**Comment by matt-raffel-kiva** [comment]
closing due to project shutdown
